project_id = "jzzpzewjowqjkewovwuj"

[functions.create-team-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.delete-team-user]
verify_jwt = false

[functions.send-delete-otp]
verify_jwt = false

[functions.verify-delete-otp]
verify_jwt = false

[functions.sync-erp-segurfact]
verify_jwt = false
