// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const DEFAULT_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const IS_VERCEL_PRODUCTION =
  typeof window !== 'undefined' &&
  window.location.hostname === 'crmpedidosonline.vercel.app';

const SUPABASE_URL = IS_VERCEL_PRODUCTION
  ? 'https://pedidos-api.169-58-90-214.sslip.io'
  : DEFAULT_SUPABASE_URL;

const SUPABASE_PUBLISHABLE_KEY = IS_VERCEL_PRODUCTION
  ? 'sb_publishable_06YNTIZ_WFZlbNrvphgoHQ_g3Ijy55l'
  : DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});