// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const DEFAULT_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SELF_HOSTED_PRODUCTION_HOSTS = new Set([
  'crmpedidosonline.vercel.app',
  'pedidos.innsanma.com',
]);

const currentHostname =
  typeof window !== 'undefined' ? window.location.hostname : '';

const IS_SELF_HOSTED_DEPLOYMENT =
  SELF_HOSTED_PRODUCTION_HOSTS.has(currentHostname) ||
  (
    currentHostname.startsWith('crmpedidosonline-') &&
    currentHostname.endsWith('.vercel.app')
  );

const SUPABASE_URL = IS_SELF_HOSTED_DEPLOYMENT
  ? 'https://pedidos-api.169-58-90-214.sslip.io'
  : DEFAULT_SUPABASE_URL;

const SUPABASE_PUBLISHABLE_KEY = IS_SELF_HOSTED_DEPLOYMENT
  ? 'sb_publishable_06YNTIZ_WFZlbNrvphgoHQ_g3Ijy55l'
  : DEFAULT_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});